services:
  db:
    container_name: web-chat-db
    image: mysql
    environment:
      - MYSQL_DATABASE=web_chat
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    networks:
      - web-chat-net
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 10s
      retries: 3
