services:
  ws:
    container_name: web-chat-ws
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["npm", "run", "ws"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web-chat-net
    ports:
      - "8081:8081"
    environment:
      - WS_HOST=0.0.0.0
      - WS_PORT=8081
      - HTTP_HOST=localhost
      - HTTP_PORT=8080
    env_file: .env.db
    healthcheck:
      test: ["CMD", "npm", "run", "ws:health"]
      interval: 3s
      timeout: 5s
      retries: 2
